# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest #windows-latest

steps:
- task: NodeTaskRunnerInstaller@0
  inputs:
    nodeVersion: '16'

- script: npm ci
  displayName: 'Install Playwright dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright browser'

- script: SECRET_KEY=Safe npm run test
  displayName: 'Run Test'